apiVersion: v1
kind: Pod
metadata:
  name: nginx-ploop3
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  nodeSelector:
    os: parallels # make sure you label your nodes to be ploop compatible 
  volumes:
  - name: test
    flexVolume:
      driver: "virtuozzo/ploop" # this must match your vendor dir
      options:
        volumeId: "golang-ploop-test"
        size: "10G"
        volumePath: "/mnt/vstorage/kube"
        vzsReplicas: "3:1/2"
